domain: chenlichao.com
name: 超哥的个人网站
description: 超哥，现居福建福州，独立IT顾问，野路子程序员，喜好阅读，坚持跑步。利用闲暇时间打理小站，分享他的观点、发现和兴趣爱好，以及他平时整理的笔记，以求增进交流，扩大影响，广交朋友。
email: clc3123@gmail.com
markdown: redcarpet
pygments: false
relative_permalinks: false
exclude:
  - vendor
  - deploy
  - bin
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - Rakefile
  - favicon.psd
  - project.aco
encoding: UTF-8
assets:
  gzip: false
